### PR TITLE
feat: add openshift serving certs to metrics endpoint, fixes RHOAIENG-1828

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Add openshift serving certs to metrics endpoint
Fixes RHOAIENG-1828

## How Has This Been Tested?

Locally applied the generated ODH config from the ODH overlay and verified the following:
* Cert secret name is correct in the service annotation
* Serving cert is created
* Cert secret name is correct in the auth proxy volume secretName
* Cert is loaded by operator in auth-proxy container

Verified metrics can be retrieved after creating clusterrolebinding from another pod serviceaccount to metrics-reader role. 

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
@tarilabs need to merge this before creating the next MR release for ODH 2.16

**Review by tarilabs — APPROVED** [review]
/lgtm

thanks Dhiraj

**Comment by tarilabs** [comment]
@dhirajsb you wanted me to perform the release train of MR by Monday, but seems this one is holding the release based on your https://github.com/opendatahub-io/model-registry-operator/pull/120#issuecomment-2264511461.
Please advise.

**Comment by dhirajsb** [comment]
@tarilabs merged this change since I was waiting on a platform PR merge as well. We are ok to do the MR release now.

**Pull request merged**
