### PR TITLE
fix: replace rbac proxy container with controller metrics server authentication and authorization, fixes RHOAIENG-13837

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Replace rbac proxy container with controller metrics server authentication and authorization
fixes RHOAIENG-13837

## How Has This Been Tested?

The following instructions describe how to test the metrics endpoint from this PR in an ODH cluster:

1. Scale down cluster odh controller to allow removing kube-rbac-proxy from MR operator:

If the odh operator was installed using Operatorhub:

```shell
oc scale deployment --replicas=0 -n openshift-operators opendatahub-operator-controller-manager
```

If the odh operator was installed using odh operator incubation branch:

```shell
oc scale deployment --replicas=0 -n opendatahub-operator-system opendatahub-operator-controller-manager
```

2. Build and use local operator image:

```shell
# build image and push
REGISTRY=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}')
docker login -u $(oc whoami) -p $(oc whoami -t) $REGISTRY
make docker-build; docker tag quay.io/opendatahub/model-registry-operator:latest $REGISTRY/opendatahub/model-registry-operator:latest; docker push $REGISTRY/opendatahub/model-registry-operator:latest
# delete existing operator deployment with kube-rbac-proxy
oc delete deployment -n opendatahub model-registry-operator-controller-manager
# apply new manifests for operator without kube-rbac-proxy
oc apply -k config/overlays/odh/
# change operator to set default cert name as set by odh operator
oc set env -n opendatahub deployment/model-registry-operator-controller-manager DEFAULT_CERT=default-modelregistry-cert
# change operator to use local image
oc set image -n opendatahub deployment/model-registry-operator-controller-manager manager=image-registry.openshift-image-registry.svc:5000/opendatahub/model-registry-operator:latest
# check that the operator is running
oc wait --for=condition=Available=true -n opendatahub deployment/model-registry-operator-controller-manager --timeout=5m
```

3. Verify that the metrics endpoint is working:

```shell
# create sleep pod to invoke metrics endpoint
oc apply -n opendatahub -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml 
# create rolebinding to allow sleep pod to invoke the metrics service like prometheus scraper
oc create clusterrolebinding --serviceaccount opendatahub:sleep --clusterrole model-registry-operator-metrics-reader sleep-rb
# start an interactive shell in sleep pod
oc exec -n opendatahub -t -i $(oc get pods -n opendatahub -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- /bin/sh
# type the following curl command in the shell to call the metrics service from the sleep pod
curl -s -k -H "Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`" https://model-registry-operator-controller-manager-metrics-service.opendatahub.svc:8443/metrics
# this should print MR operator metrics
# exit interactive shell by typing exit
```

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
@lburgazzoli can you give this a look to make sure I haven't missed anything in the switch to using controller-runtime metrics server? 
I have verified it locally by following the detailed included instructions.

**Comment by dhirajsb** [comment]
The model-registry-operator-metrics-reader role is the same as other operator metrics reader roles:
```
[dbokde@dbokde-thinkpadp16vgen1 model-registry-operator (fix/metrics-rbac-proxy =)]$ kc describe clusterrole opendatahub-operator-metrics-reader 
Name:         opendatahub-operator-metrics-reader
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
             [/metrics]         []              [get]
[dbokde@dbokde-thinkpadp16vgen1 model-registry-operator (fix/metrics-rbac-proxy =)]$ kc describe clusterrole model-registry-operator-metrics-reader 
Name:         model-registry-operator-metrics-reader
Labels:       app.kubernetes.io/component=metrics
              app.kubernetes.io/created-by=model-registry-operator
              app.kubernetes.io/instance=metrics-reader
              app.kubernetes.io/managed-by=kustomize
              app.kubernetes.io/name=clusterrole
              app.kubernetes.io/part-of=model-registry-operator
              app.opendatahub.io/model-registry-operator=true
              component.opendatahub.io/name=model-registry-operator
              control-plane=model-registry-operator
              opendatahub.io/component=true
Annotations:  internal.config.kubernetes.io/previousKinds: ClusterRole
              internal.config.kubernetes.io/previousNames: model-registry-operator-metrics-reader
              internal.config.kubernetes.io/previousNamespaces: _non_namespaceable_
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
             [/metrics]         []              [get]
```

**Comment by lburgazzoli** [comment]
> @lburgazzoli can you please give this a look to make sure I haven't missed anything in the switch to using controller-runtime metrics server? I have verified it locally by following the included detailed instructions.

I still to have to try the new controller-runtime machinery myself so I may still missing something, however with my actual knowledge it looks good

**Review by Al-Pragliola — APPROVED** [review]
LGTM

code seems to follow the info from https://book.kubebuilder.io/reference/metrics#metrics-protection, I also tested on my dev cluster with the code snippet provided and everything works as intended, I got the metrics with the right clusterrolebinding and the error `Authorization denied for user system:serviceaccount:opendatahub:sleep` without it, good job!

**Review by lburgazzoli — APPROVED** [review]

**Review by lphiri — COMMENTED** [review]
@dhirajsb  how will the certs be configured/generated in production?
Otherwise changes look good from code perspective.

**Comment by dhirajsb** [comment]
@lphiri OpenShift [serving certs](https://github.com/opendatahub-io/model-registry-operator/blob/a5e4b928e149335e35116bf933d5668950b6bd15/config/overlays/odh/patches/auth_proxy_service_patch.yaml#L6) are used to generate certs for the metrics endpoint. 
They are mounted using a [volume mount](https://github.com/opendatahub-io/model-registry-operator/blob/a5e4b928e149335e35116bf933d5668950b6bd15/config/overlays/odh/patches/manager_auth_proxy_patch.yaml#L28) and passed into the controller using the [new metrics parameters](https://github.com/opendatahub-io/model-registry-operator/blob/a5e4b928e149335e35116bf933d5668950b6bd15/config/overlays/odh/patches/manager_auth_proxy_patch.yaml#L28) I added. The controller runtime also watches the certs and will update them when secrets are rotated.

**Comment by dhirajsb** [comment]
I updated a wrong link in the previous comment.

**Review by lphiri — APPROVED** [review]
LGTM

**Pull request merged**
