### PR TITLE
feat: add support for configmap CA certs, fixes RHOAIENG-14601

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Add support for configmap CA certs
Fixes RHOAIENG-14601

## How Has This Been Tested?

Changed secure-db sample to use configmap for CA, and tested deployment in local cluster

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
Depends on merging #147 first

**Review by tarilabs — COMMENTED** [review]
I understand a configmap is created for holding the root CA used for the DB certificates.

I understand this is now a parameter in the MR CR,
so that the operator can use (when provided) the CM to mount the root CA -- which then MLMD can use to communicate with the DB

In general,
/lgtm 

is this the way also DSP is doing this? I saw some slack threads but was not there for the conclusion

Thank you!

**Comment by dhirajsb** [comment]
@tarilabs yes, DSP also uses configmap, but its not something they expose to users in the Dashboard right now.

**Review by Al-Pragliola — APPROVED** [review]
lgtm

**Pull request merged**
